Prefecture.find_or_create_by(name: "Hokkaido")
Prefecture.find_or_create_by(name: "Tokyo")
Prefecture.find_or_create_by(name: "Aichi")
Prefecture.find_or_create_by(name: "Fukuoka")
Prefecture.find_or_create_by(name: "Osaka")
User.find_or_create_by(name:'Taro',gender: 1, birthday: '21/4/1971',prefecture_id: 2)
User.find_or_create_by(name:'Jiro',gender: 1, birthday: '11/1/1972',prefecture_id: 2)
User.find_or_create_by(name:'Yoko',gender: 2, birthday: '10/6/1985',prefecture_id: 3)
User.find_or_create_by(name:'Ken',gender: 1, birthday: '12/1/2009',prefecture_id: 4)
User.find_or_create_by(name:'Nobu',gender: 1, birthday: '4/12/1969',prefecture_id: 1)
User.find_or_create_by(name:'kana',gender: 2, birthday: '6/2/1999',prefecture_id: 5)